"""Generate the paper's numbers and tables from the results files.

Run from the repository root:  python src/make_paper_tables.py

Reads only CSV files under results/ (not the raw data) and writes to paper/generated/:

    numbers.tex              one \\newcommand per number quoted in the text
    tab_routes.tex           events, trips and stops per route
    tab_splits.tex           R2 by model and evaluation split
    tab_splits_rmse.tex      RMSE by model and evaluation split
    tab_fewshot.tex          few-shot experiment: mean R2 by k, model and condition
    tab_fewshot_routes.tex   few-shot experiment: R2 per route (pooled condition)

Nothing in paper/generated/ is edited by hand.
"""
import pandas as pd

from data import REPO_ROOT

RESULTS = REPO_ROOT / "results"
OUT = REPO_ROOT / "paper" / "generated"
HEADER = "% Generated by src/make_paper_tables.py -- do not edit by hand.\n"

MODEL_LABEL = {"GlobalMean": "Global mean", "StopMean": "Stop mean",
               "RouteStopMean": "Route $\\times$ stop mean", "Ridge": "Ridge",
               "XGBoost": "XGBoost", "LightGBM": "LightGBM", "TabPFN": "TabPFN"}
BASELINES = ["GlobalMean", "StopMean", "RouteStopMean", "Ridge"]
MODELS = ["XGBoost", "LightGBM", "TabPFN"]
MINUS = "$-$"


def num(x, digits=3):
    s = f"{abs(x):.{digits}f}"
    return (MINUS if x < 0 and float(s) != 0 else "") + s


def mean_std(values, digits=3):
    values = pd.Series(values).dropna()
    if values.empty:
        return "--"
    if len(values) == 1:
        return num(values.iloc[0], digits)
    return f"{num(values.mean(), digits)} $\\pm$ {values.std():.{digits}f}"


def write(name, text):
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / name).write_text(HEADER + text, encoding="utf-8", newline="\n")
    print("wrote", (OUT / name).relative_to(REPO_ROOT))


# ---------------------------------------------------------------- numbers
def numbers(log, few):
    facts = pd.read_csv(RESULTS / "dataset" / "dataset_summary.csv").set_index("key")["value"]
    integer = lambda k: f"{int(float(facts[k])):,}".replace(",", "{,}")
    date = lambda k: f"{pd.Timestamp(facts[k]).day} {pd.Timestamp(facts[k]).strftime('%B %Y')}"
    macros = {
        "RawRows": integer("raw_rows"), "RawColumns": integer("raw_columns"),
        "Events": integer("events"), "MultiCopyEvents": integer("multi_copy_events"),
        "MaxCopies": integer("max_copies_per_event"),
        "DelayConflictEvents": integer("delay_conflict_events"),
        "DateMin": date("date_min"), "DateMax": date("date_max"),
        "DistinctDates": integer("distinct_dates"),
        "NRoutes": integer("n_routes"), "NTrips": integer("n_trips"),
        "NSailings": integer("n_sailings"), "MaxDatesPerTrip": integer("max_dates_per_trip"),
        "TripsSeveralDatesPct": f"{float(facts['trips_on_several_dates_pct']):.0f}",
        "NStops": integer("n_stops"), "NVehicles": integer("n_vehicles"),
        "WinsorLow": f"{MINUS}{abs(int(float(facts['winsor_low'])))}",
        "WinsorHigh": integer("winsor_high"),
        "RawDelayMax": integer("raw_delay_max"),
        "ClippedLow": integer("events_clipped_low"), "ClippedHigh": integer("events_clipped_high"),
        "TargetMean": f"{float(facts['target_mean']):.1f}",
        "TargetStd": f"{float(facts['target_std']):.1f}",
        "MissingStopEvents": integer("events_missing_stop_id"),
        "CutoffDate": date("time_split_last_date"),
        "EventsAfterCutoff": integer("events_after_cutoff"),
        "TimeTrainRows": integer("time_train_rows"), "TimeTrainDates": integer("time_train_dates"),
        "TimeTrainLast": date("time_train_last"), "TimeTestFirst": date("time_test_first"),
        "TimeTestDates": integer("time_test_dates"),
        "TimeTestPeriodRows": integer("time_test_period_rows"),
        "FixedTestCap": integer("fixed_test_cap"),
        "FewshotTestCap": f"{int(few.n_test_rows.max()):,}".replace(",", "{,}"),
        "FewshotSeeds": str(few.random_seed.nunique()),
        "FewshotTabpfnRuns": str(int((few.model == "TabPFN").sum())),
    }
    trip = log[(log.experiment_name == "final_5seed_trip_grouped") & (log.feature_set == "all_features")]
    macros["TripSeeds"] = str(trip.random_seed.nunique())
    macros["TimeRowRatio"] = f"{float(facts['time_train_rows']) / 10000:.0f}"
    macros["TripRowRatio"] = f"{0.8 * float(facts['events']) / 10000:.0f}"
    text = "".join(f"\\newcommand{{\\{k}}}{{{v}}}\n" for k, v in macros.items())
    write("numbers.tex", text + result_macros(log))


def cond_key(condition):
    # macro keys carry no underscore: pooled, pooled10k, targetonly
    return condition.replace("_", "")


def keyed(prefix, key, value):
    return f"\\expandafter\\def\\csname {prefix}@{key}\\endcsname{{{value}}}\n"


def accessor(name, prefix, n_args):
    args = "@".join(f"#{i}" for i in range(1, n_args + 1))
    return f"\\newcommand{{\\{name}}}[{n_args}]{{\\csname {prefix}@{args}\\endcsname}}\n"


def result_macros(log):
    """Result numbers for the prose, looked up by name:

    \\res{split}{model}    mean (with +/- std where repeated)   \\resm{split}{model}  mean only
    \\fs{cond}{model}{k}   few-shot mean R2 over routes          \\fssd  std over routes
    \\fsmin, \\fsmax        lowest and highest route             \\fspos routes with R2 > 0
    \\fswins{cond}{k}      routes where TabPFN beats both boosters
    \\fslosers{cond}{k}    the other routes, by name
    \\fst..., as above, for the time-respecting few-shot experiment
    """
    out = "% --- results by split: \\res{split}{model}, \\resm{split}{model}\n"
    out += accessor("res", "res", 2) + accessor("resm", "resm", 2)
    out += accessor("resmin", "resmin", 2) + accessor("resmax", "resmax", 2)
    routes = pd.read_csv(RESULTS / "dataset" / "dataset_routes.csv")
    big, small = routes.loc[routes.events.idxmax()], routes.loc[routes.events.idxmin()]
    late, early = routes.loc[routes.mean_delay.idxmax()], routes.loc[routes.mean_delay.idxmin()]
    for name, value in [("LargestRoute", big.route_id), ("LargestRouteShare", f"{big.share_pct:.0f}"),
                        ("SmallestRoute", small.route_id), ("SmallestRouteShare", f"{small.share_pct:.0f}"),
                        ("LatestRoute", late.route_id), ("LatestRouteDelay", num(late.mean_delay, 0)),
                        ("EarliestRoute", early.route_id), ("EarliestRouteDelay", num(early.mean_delay, 0)),
                        ("EventsPerTripMin", f"{routes.rows_per_trip.min():.0f}"),
                        ("EventsPerTripMax", f"{routes.rows_per_trip.max():.0f}")]:
        out += f"\\newcommand{{\\{name}}}{{{value}}}\n"
    runlog = RESULTS / "experiments" / "tabpfn_run_log.csv"
    if runlog.is_file():
        versions = sorted(pd.read_csv(runlog).served_default_model_version.astype(str).unique())
        out += f"\\newcommand{{\\ServedModel}}{{{', '.join(versions)}}}\n"
    cells = split_cells(log, "R2")
    for (model, split), values in cells.items():
        v = pd.Series(values).dropna()
        if v.empty:
            continue
        out += keyed("res", f"{split}@{model}", mean_std(v))
        out += keyed("resm", f"{split}@{model}", num(v.mean()))
        out += keyed("resmin", f"{split}@{model}", num(v.min()))
        out += keyed("resmax", f"{split}@{model}", num(v.max()))
    tab = pd.Series(cells[("TabPFN", "time")])
    out += f"\\newcommand{{\\TimeTabMin}}{{{num(tab.min())}}}\n\\newcommand{{\\TimeTabMax}}{{{num(tab.max())}}}\n"
    out += f"\\newcommand{{\\TimeTabRuns}}{{{len(tab)}}}\n"

    t = log[(log.split_type == "time") & (log.random_seed == 42)
            & log.experiment_name.isin(["time_split", "equal_data_10k", "naive_baselines"])
            & log.model.isin(["XGBoost", "LightGBM", "Ridge"])]
    wide = t.pivot_table(index=["experiment_name", "model"], columns="feature_set", values="R2")
    wide.loc[("time_split", "Ridge"), "all_features"] = wide.loc[("naive_baselines", "Ridge"), "all_features"]
    change = (wide["no_date_features"] - wide["all_features"]).dropna().abs()
    out += f"\\newcommand{{\\NoDateMaxChange}}{{{change.max():.3f}}}\n"
    out += f"\\newcommand{{\\NoDateCells}}{{{len(change)}}}\n"

    for stem, p in [("fewshot", "fs"), ("fewshot_time", "fst")]:
        path = RESULTS / "experiments" / f"{stem}_summary.csv"
        if not path.is_file():
            continue
        s = pd.read_csv(path)
        r = pd.read_csv(RESULTS / "experiments" / f"{stem}_per_route.csv")
        out += f"% --- {stem}: \\{p}{{condition}}{{model}}{{k}} etc.\n"
        for name in ["", "sd", "min", "max", "pos"]:
            out += accessor(p + name, p + name, 3)
        out += accessor(p + "wins", p + "wins", 2) + accessor(p + "losers", p + "losers", 2)
        for x in s.itertuples():
            key = f"{cond_key(x.condition)}@{x.model}@{x.k}"
            out += keyed(p, key, num(x.R2_mean)) + keyed(p + "sd", key, f"{x.R2_std:.3f}")
            out += keyed(p + "min", key, num(x.R2_min)) + keyed(p + "max", key, num(x.R2_max))
            routes = r[(r.condition == x.condition) & (r.model == x.model) & (r.k == x.k)]
            out += keyed(p + "pos", key, int((routes.R2 > 0).sum()))
        duel = r[r.model.isin(MODELS) & r.condition.isin(["pooled", "target_only"])].pivot_table(
            index=["condition", "k", "route"], columns="model", values="R2").dropna()
        duel["win"] = duel["TabPFN"] > duel[["XGBoost", "LightGBM"]].max(axis=1)
        for (cond, k), g in duel.groupby(level=[0, 1]):
            losers = [route for (_, _, route), w in g["win"].items() if not w]
            out += keyed(p + "wins", f"{cond_key(cond)}@{k}", int(g["win"].sum()))
            out += keyed(p + "losers", f"{cond_key(cond)}@{k}", ", ".join(losers) if losers else "none")
    return out


# ---------------------------------------------------------------- routes
def routes_table():
    r = pd.read_csv(RESULTS / "dataset" / "dataset_routes.csv")
    rows = "".join(
        f"{x.route_id} & {x.events:,} & {x.share_pct:.1f} & {x.trips:,} & {x.stops} & "
        f"{x.rows_per_trip:.1f} & {num(x.mean_delay, 1)} & {x.std_delay:.1f} \\\\\n"
        for x in r.itertuples()).replace(",", "{,}")
    total = f"All & {r.events.sum():,} & 100.0 & {r.trips.sum():,} & & & & \\\\\n".replace(",", "{,}")
    write("tab_routes.tex",
          "\\begin{tabular}{lrrrrrrr}\n\\hline\n"
          "Route & Events & Share (\\%) & Trip ids & Stops & Events/trip id & Mean delay (s) & Std (s) \\\\\n"
          "\\hline\n" + rows + "\\hline\n" + total + "\\hline\n\\end{tabular}\n")


# ---------------------------------------------------------------- splits
def split_cells(log, metric):
    """{(row label, column): list of values}"""
    A = log[log.feature_set == "all_features"]
    cells = {}

    def put(row, col, frame):
        cells[(row, col)] = frame[metric].tolist()

    naive = pd.read_csv(RESULTS / "main_pipeline" / "naive_split_results.csv").set_index("model")
    route = pd.read_csv(RESULTS / "main_pipeline" / "route_split_by_seed.csv")
    for m in MODELS:
        cells[(m, "random")] = [naive.loc[m, metric]]
        put(m, "trip", A[(A.experiment_name == "final_5seed_trip_grouped") & (A.model == m)])
        cells[(m, "route")] = route[route.model == m][metric].tolist()
        put(m, "time", A[(A.experiment_name == "time_split") & (A.model == m)])
    for m in BASELINES:
        for col, split in [("trip", "trip_grouped"), ("route", "route_grouped"), ("time", "time")]:
            put(m, col, A[(A.experiment_name == "naive_baselines") & (A.split_type == split) & (A.model == m)])
    for m in ["XGBoost", "LightGBM"]:
        for col, split in [("trip", "trip_grouped"), ("time", "time")]:
            put(m + "10k", col, A[(A.experiment_name == "equal_data_10k") & (A.split_type == split) & (A.model == m)])
        put(m + "50k", "time", A[(A.experiment_name == "equal_data_50k") & (A.model == m)])
    put("TabPFN50k", "time", A[A.experiment_name == "time_split_tabpfn_50k"])
    put("TabPFNall", "time", A[A.experiment_name == "time_split_tabpfn_all"])
    # TabPFN on the first three splits: the August figures stay available as "TabPFNaug";
    # where the re-run on the current model is complete for a split, it is used instead.
    for col, split, n_runs in [("random", "random", 1), ("trip", "trip_grouped", 5), ("route", "route_grouped", 5)]:
        cells[("TabPFNaug", col)] = cells[("TabPFN", col)]
        rerun = A[(A.experiment_name == "tabpfn_rerun") & (A.split_type == split) & (A.model == "TabPFN")]
        if len(rerun) == n_runs:
            put("TabPFN", col, rerun)
    return cells


def splits_table(log, metric, name, digits):
    cells = split_cells(log, metric)
    cols = ["random", "trip", "route", "time"]
    order = [(m, MODEL_LABEL[m]) for m in BASELINES] + \
            [("XGBoost", "XGBoost, all rows"), ("LightGBM", "LightGBM, all rows"), ("TabPFNall", "TabPFN, all rows"),
             ("XGBoost50k", "XGBoost, 50{,}000 rows"), ("LightGBM50k", "LightGBM, 50{,}000 rows"),
             ("TabPFN50k", "TabPFN, 50{,}000 rows"),
             ("XGBoost10k", "XGBoost, 10{,}000 rows"), ("LightGBM10k", "LightGBM, 10{,}000 rows"),
             ("TabPFN", "TabPFN, 10{,}000 rows")]
    order = [(k, label) for k, label in order if any(cells.get((k, c)) for c in cols)]
    lines = []
    for key, label in order:
        if key in ("XGBoost", "XGBoost50k", "XGBoost10k"):
            lines.append("\\hline\n")
        lines.append(label + " & " + " & ".join(mean_std(cells.get((key, c), []), digits) for c in cols) + " \\\\\n")
    write(name,
          "\\begin{tabular}{lrrrr}\n\\hline\n"
          "Model & Random & Trip-grouped & Unseen routes & Time \\\\\n\\hline\n"
          + "".join(lines) + "\\hline\n\\end{tabular}\n")


# ---------------------------------------------------------------- few-shot
def fewshot_mean_table(stem, name):
    s = pd.read_csv(RESULTS / "experiments" / f"{stem}_summary.csv")
    ks = sorted(s.k.unique())
    blocks = [("pooled", "Pooled (other 8 routes + $k$ rows)", MODELS + ["Ridge", "RouteStopMean", "GlobalMean"]),
              ("pooled_10k", "Pooled, TabPFN's 10{,}000 rows", ["XGBoost", "LightGBM"]),
              ("target_only", "Target-only ($k$ rows)", MODELS + ["Ridge", "RouteStopMean", "GlobalMean"])]
    body = ""
    for cond, title, models in blocks:
        body += f"\\hline\n\\multicolumn{{{len(ks) + 1}}}{{l}}{{\\emph{{{title}}}}} \\\\\n"
        for m in models:
            row = s[(s.condition == cond) & (s.model == m)].set_index("k")["R2_mean"]
            body += MODEL_LABEL[m] + " & " + " & ".join(num(row[k]) if k in row.index else "--" for k in ks) + " \\\\\n"
    write(name,
          "\\begin{tabular}{l" + "r" * len(ks) + "}\n\\hline\n"
          "Model & " + " & ".join(f"$k={k:,}$".replace(",", "{,}") for k in ks) + " \\\\\n"
          + body + "\\hline\n\\end{tabular}\n")


def fewshot_tables():
    fewshot_mean_table("fewshot", "tab_fewshot.tex")
    if (RESULTS / "experiments" / "fewshot_time_summary.csv").is_file():
        fewshot_mean_table("fewshot_time", "tab_fewshot_time.tex")
    ks = sorted(pd.read_csv(RESULTS / "experiments" / "fewshot_summary.csv").k.unique())
    p = pd.read_csv(RESULTS / "experiments" / "fewshot_per_route.csv")
    p = p[p.condition == "pooled"]
    routes = sorted(p.route.unique())
    body = ""
    for m in MODELS:
        body += f"\\hline\n\\multicolumn{{{len(ks) + 1}}}{{l}}{{\\emph{{{MODEL_LABEL[m]}}}}} \\\\\n"
        t = p[p.model == m].pivot(index="route", columns="k", values="R2")
        for r in routes:
            body += r + " & " + " & ".join(num(t.loc[r, k]) for k in ks) + " \\\\\n"
    trips = p[p.model == "XGBoost"].pivot(index="route", columns="k", values="n_target_trips")
    body += f"\\hline\n\\multicolumn{{{len(ks) + 1}}}{{l}}{{\\emph{{Distinct trips in the $k$ rows (mean over seeds)}}}} \\\\\n"
    for r in routes:
        body += r + " & " + " & ".join(f"{trips.loc[r, k]:,.0f}".replace(",", "{,}") for k in ks) + " \\\\\n"
    write("tab_fewshot_routes.tex",
          "\\begin{tabular}{l" + "r" * len(ks) + "}\n\\hline\n"
          "Route & " + " & ".join(f"$k={k:,}$".replace(",", "{,}") for k in ks) + " \\\\\n"
          + body + "\\hline\n\\end{tabular}\n")


def main():
    log = pd.read_csv(RESULTS / "experiments" / "experiment_results.csv")
    log = log.drop_duplicates(["experiment_name", "feature_set", "split_type", "model", "random_seed"])
    few = pd.read_csv(RESULTS / "experiments" / "fewshot_results.csv")
    numbers(log, few)
    routes_table()
    splits_table(log, "R2", "tab_splits.tex", 3)
    splits_table(log, "RMSE", "tab_splits_rmse.tex", 1)
    fewshot_tables()


if __name__ == "__main__":
    main()
